fix(Views/V2) do not cast types when sorting
moderntribe/the-events-calendar pull request #3292
Opened 2020-10-06 11:07 UTC by lucatume

2020-10-06 11:10 UTC, tr1b0t reviewed
:no_entry_sign: 2 error(s)
:warning: 4 warning(s)

2020-10-06 11:10 UTC, tr1b0t commented on src/Tribe/Views/V2/Rest_Endpoint.php
> +		$request = new Request( 'POST', static::ROOT_NAMESPACE . '/html' );
:warning: Equals sign not aligned with surrounding assignments; expected 3 spaces but found 1 space

<sub>hash: 1782e1487691599d5deaab835a6ec696</sub>

2020-10-06 11:10 UTC, tr1b0t commented on src/Tribe/Views/V2/Rest_Endpoint.php
> +		$source = isset( $_POST ) ? $_POST : $_GET;
* :warning: Equals sign not aligned with surrounding assignments; expected 2 spaces but found 1 space
* :no_entry_sign: Processing form data without nonce verification.
* :no_entry_sign: Processing form data without nonce verification.
* :warning: Processing form data without nonce verification.

<sub>hash: de57cc50f8ca156487c6240e30c93ec6</sub>

2020-10-06 11:10 UTC, tr1b0t commented on src/Tribe/Views/V2/View.php
> +		$endpoint      = tribe( Rest_Endpoint::class );
:warning: Equals sign not aligned correctly; expected 1 space but found 6 spaces

<sub>hash: d0b95eb1e4d2fc897af4254df8f1eaf6</sub>

2020-10-06 11:18 UTC, tr1b0t reviewed
:no_entry_sign: 2 error(s)
:warning: 1 warning(s)

2020-10-06 11:18 UTC, tr1b0t commented on src/Tribe/Views/V2/Rest_Endpoint.php
> +		$source  = isset( $_POST ) ? $_POST : $_GET;
* :no_entry_sign: Processing form data without nonce verification.
* :no_entry_sign: Processing form data without nonce verification.
* :warning: Processing form data without nonce verification.

<sub>hash: 61904cd92e27a45c75e15386f8e25046</sub>

2020-10-07 04:22 UTC, paulmskim submitted a review, later dismissed
FE looks good, BE looks good from what I can see.

2020-10-12 03:48 UTC, bordoni submitted a review, later dismissed
Do we have a PR with modifications to the PRO views? Related to: `data-view-rest-method`

2020-10-12 08:11 UTC, lucatume commented
> Do we have a PR with modifications to the PRO views? Related to: `data-view-rest-method`

https://github.com/moderntribe/events-pro/pull/1595

2020-10-12 14:45 UTC, Camwyn requested changes
Couple small docblock tweaks and a question:
We cover GET for BC - should we have a test to cover that BC?

2020-10-12 14:45 UTC, Camwyn commented on src/Tribe/Views/V2/Rest_Endpoint.php
> +	 * Returns the filtered HTTP method Views should use to fetch their content from the backend endpoint..
```suggestion
	 * Returns the filtered HTTP method Views should use to fetch their content from the backend endpoint.
```

2020-10-12 14:45 UTC, Camwyn commented on src/Tribe/Views/V2/Rest_Endpoint.php
> +		 *                       `GET`. Invalid values will be defaulted to `POST`.
```suggestion
		 *                       `GET`. Invalid values will be set to the default `POST`.
```

2020-10-12 15:23 UTC, jesseeproductions approved these changes

2020-10-13 16:04 UTC, bordoni submitted a review, later dismissed

2020-10-14 11:04 UTC, merged