Correct the iCal export link for the current month.
moderntribe/the-events-calendar pull request #3293
Opened 2020-10-06 15:15 UTC by Camwyn

The function that handles the link uses getLink() from Tribe__Events__Main.
For the current month, pretty permalinks will contain "now" for the month.

This replaces that "now" with the current month in 'Y-m' format for the iCal link only.

:camera: http://p.tri.be/dmNwm4

[TEC-3575]

2020-10-06 15:19 UTC, tr1b0t commented on src/Tribe/iCal.php
> +		$url = str_replace( '/now/', '/' . date( 'Y-m' ) . '/', $url );
:no_entry_sign: date() is affected by runtime timezone changes which can cause date/time to be incorrectly displayed. Use gmdate() instead.

<sub>hash: 5201e70188e510944596fc849c07fab7</sub>

2020-10-07 13:07 UTC, lucatume requested changes
Add tests, please.

2020-10-07 13:07 UTC, lucatume commented on src/Tribe/iCal.php
> +		$url = str_replace( '/now/', '/' . gmdate( 'Y-m' ) . '/', $url );
Do not use any system-based date handling (`date`, `gmdate`); use `Tribe__Date__Utils::build_date_object` instead.

2020-10-07 13:07 UTC, lucatume commented on src/Tribe/iCal.php
> +		$url = str_replace( '/now/', '/' . gmdate( 'Y-m' ) . '/', $url );
I would have a more precise targeting of the `now` string:

1. There could not be a trailing `/`.
2. "now" is the English version of this, what about localized strings?

2020-10-07 16:12 UTC, lucatume approved these changes

2020-10-07 16:16 UTC, merged