Tweak widget form layout.
moderntribe/the-events-calendar pull request #3319
Opened 2020-10-27 16:36 UTC by Camwyn

In an effort to make the widget form match the original as much as possible:

Handle `section_start` and `section_end` injected fields.
Add form section start template, utilize it.
Add common branch with styles for form section.

📷 http://p.tri.be/YijDvd

Requires: https://github.com/moderntribe/tribe-common/pull/1468

2020-10-27 17:56 UTC, paulmskim requested changes

2020-10-27 17:56 UTC, paulmskim commented on src/admin-views/widgets/components/input-section-start.php
> +	<?php endif; ?>
This is not a standalone component and cannot be reused without the ending `</div>` in the `src/admin-views/widgets/list.php` file. Better to put this logic together with the `</div>`

2020-10-27 23:42 UTC, tr1b0t reviewed
:no_entry_sign: 1 error(s)

2020-10-27 23:42 UTC, tr1b0t commented on src/admin-views/widgets/list.php
> +			// Note: the actual widget title/handle is an <h3>
:no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: 68dc2d19d787cadceeec1fa54bd1ee1f</sub>

2020-10-28 04:13 UTC, paulmskim submitted a review, later dismissed

2020-10-30 14:19 UTC, tr1b0t reviewed
:no_entry_sign: 4 error(s)

2020-10-30 14:19 UTC, tr1b0t commented on src/admin-views/widgets/list.php
> +			<?php endif;
:no_entry_sign: Opening PHP tag must be on a line by itself

<sub>hash: ef998bcb328309646e79988025627f17</sub>

2020-10-30 14:19 UTC, tr1b0t commented on src/admin-views/widgets/list.php
> +		continue;
:no_entry_sign: Line indented incorrectly; expected at least 3 tabs, found 2

<sub>hash: f754ad41d130e6474134b83d4fea7d22</sub>

2020-10-30 14:19 UTC, tr1b0t commented on src/admin-views/widgets/list.php
> +	if ( false !== stripos( $field_id, 'section_end' ) ) : ?>
:no_entry_sign: Closing PHP tag must be on a line by itself

<sub>hash: 1b070ced487934f1e0adb2cfb0219a8b</sub>

2020-10-30 14:19 UTC, tr1b0t commented on src/admin-views/widgets/list.php
> +		<?php continue;
:no_entry_sign: Opening PHP tag must be on a line by itself

<sub>hash: dff4ad5b8175557e5e28e274020a7a4d</sub>

2020-11-04 14:06 UTC, lucatume requested changes

2020-11-04 14:06 UTC, lucatume commented on src/admin-views/widgets/list.php
> +	if ( false !== stripos( $field_id, 'section_start' ) ) {
Since we want, here, to check for field ids that **start** with `section_start`, I would use `0 === stripos`.

2020-11-04 14:06 UTC, lucatume commented on src/admin-views/widgets/list.php
> +	if ( false !== stripos( $field_id, 'section_end' ) ) {
Same here: since we're checking for fields IDs that start with `section_end`, I would use `0 === stripos` here.

2020-11-05 04:20 UTC, paulmskim approved these changes

2020-11-06 10:55 UTC, lucatume approved these changes

2020-11-06 14:33 UTC, merged