Feature/tec 3630 smooth transition v1 to v2
moderntribe/the-events-calendar pull request #3322
Opened 2020-10-28 18:32 UTC by jesseeproductions

_Ref:_ [TEC-3630](https://moderntribe.atlassian.net/browse/TEC-3630)
_Ref:_ [TEC-3593](https://moderntribe.atlassian.net/browse/TEC-3593)

2020-10-29 00:22 UTC, tr1b0t reviewed
:no_entry_sign: 11 error(s)

2020-10-29 00:22 UTC, tr1b0t commented on src/Tribe/Views/V2/Widgets/Compatibility.php
> +	public function switch_to_v1_compatibility() {
:no_entry_sign: Additional blank lines found at end of doc comment

<sub>hash: be297244ace0dc2fd73ffa29408cbace</sub>

2020-10-29 00:22 UTC, tr1b0t commented on src/Tribe/Views/V2/Widgets/Compatibility.php
> +		// if Pro is disabled, use the defaults.
* :no_entry_sign: Please, make sure that a callback to `'tribe_plugins_loaded'` filter is returning void intentionally.
* :no_entry_sign: Please, make sure that a callback to `'tribe_plugins_loaded'` filter is always returning some value.

<sub>hash: c27f54fa50c2ebb540197cdf751691e0</sub>

2020-10-29 00:22 UTC, tr1b0t commented on src/Tribe/Views/V2/Widgets/Service_Provider.php
> +		$this->container->singleton( Compatibility::class, Compatibility::class, ['hooks'] );
* :no_entry_sign: Missing space after array opener.
* :no_entry_sign: Missing space after array opener.
* :no_entry_sign: Missing space before array closer.
* :no_entry_sign: Missing space before array closer.

<sub>hash: ecc87719c66e9379c3c03b4d70ee2fcf</sub>

2020-10-29 00:22 UTC, tr1b0t commented on src/Tribe/Views/V2/Widgets/Service_Provider.php
> +		$this->container->singleton( 'pro.views.v2.widgets.compatibility', Compatibility::class, ['hooks'] );
* :no_entry_sign: Missing space after array opener.
* :no_entry_sign: Missing space after array opener.
* :no_entry_sign: Missing space before array closer.
* :no_entry_sign: Missing space before array closer.

<sub>hash: 9e205c5a88e9d6acaa5a2b9ed7fcf57c</sub>

2020-10-29 15:28 UTC, lucatume requested changes
Please, add tests to cover the option filtering: having a clear indication of what is happening and what the filtering does might make this on-the-fly migration easier to understand and cover this piece of code from regression.

2020-10-29 15:28 UTC, lucatume commented on src/Tribe/Views/V2/Widgets/Compatibility.php
> +		// if Pro is disabled, use the defaults.
```suggestion
		// If Pro is disabled, use the defaults.
```

2020-10-29 15:28 UTC, lucatume commented on src/Tribe/Views/V2/Widgets/Compatibility.php
> +
```suggestion
```

Here and elsewhere, remove blank lines at start and end of function and methods definitions.

2020-10-29 15:28 UTC, lucatume commented on src/Tribe/Views/V2/Widgets/Compatibility.php
> +
Same removal of blank lines of blocks, here and elsewhere.

2020-10-29 15:28 UTC, lucatume commented on src/Tribe/Views/V2/Widgets/Compatibility.php
> +	 * v1 free list widget to the v1 Pro advanced list widget.
Please, add a note here about why this method should live in TEC and not PRO, and why.
It's not an immediate intuition and someone with good intentions might think to move it in the future.

2020-10-29 15:35 UTC, Camwyn requested changes

2020-10-29 15:35 UTC, Camwyn commented on src/Tribe/Views/V2/Widgets/Compatibility.php
> +		// Combine arrays and key the array keys.
```suggestion
		// Combine arrays and keep the array keys.
```
?

2020-10-29 15:35 UTC, Camwyn commented on src/Tribe/Views/V2/Widgets/Compatibility.php
> +	 * @return array<int,mixed> $widgets An array of saved widgets.
```suggestion
	 * @return array<int,mixed> $widgets The modified array of saved widgets.
```

2020-11-24 18:24 UTC, lucatume approved these changes

2020-11-24 19:34 UTC, Camwyn submitted a review, later dismissed

2020-11-24 19:34 UTC, tr1b0t reviewed
:no_entry_sign: 2 error(s)
:warning: 2 warning(s)

2020-11-24 19:34 UTC, tr1b0t commented on src/admin-views/widgets/components/radio.php
> +		id="<?php echo esc_attr( $id ) . '-' . strtolower( esc_attr( $button_value ) ); ?>"
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'strtolower'.
* :warning: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')'

<sub>hash: d868937ea6dceb2e75d0e1c7f682efc1</sub>

2020-11-24 19:34 UTC, tr1b0t commented on src/admin-views/widgets/components/radio.php
> +		for="<?php echo esc_attr( $id ) . '-' . strtolower( esc_attr( $button_value ) ); ?>"
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'strtolower'.
* :warning: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not ')'

<sub>hash: 9f79e689d085f79ffebc163a0c94cf4c</sub>

2020-11-24 20:00 UTC, Camwyn approved these changes

2020-11-24 22:14 UTC, merged