Fix/TEC-3569 - Fix Eventbrite status filter to not return 'do_not_override' and handle Eventbrite's additional statuses
moderntribe/the-events-calendar pull request #3324
Opened 2020-10-30 15:57 UTC by codingmusician

2020-10-30 15:59 UTC, tr1b0t reviewed
:no_entry_sign: 74 error(s)

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                // override status if set within import
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: 3c3ded45b09aed7017bb50771a649e11</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                $status = isset( $record->meta['post_status'] ) ? $record->meta['post_status'] : $post_status;
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: f7c50f38837a34c5910067b3366bc4c3</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                if ( 'do_not_override' === $status ) {
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 2 tabs, found 4

<sub>hash: 3e687dc957d4d0ac2b3df32db37ba425</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                    if( isset($event['eventbrite']->status) ){
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 3 tabs, found 5
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after IF keyword; 0 found
* :no_entry_sign: There must be a space between if and the first parenthesis '('
* :no_entry_sign: Expected 1 spaces after opening parenthesis; 0 found
* :no_entry_sign: Expected 1 spaces before closing parenthesis; 0 found
* :no_entry_sign: There must be a single space after the first parenthesis
* :no_entry_sign: There must be a single space before the last parenthesis
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: 4aa33bdd7c154a62c5386c7270781642</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                        // draft if set, otherwise publish
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: c4e434d5a54abf100ccaf4105795bcfb</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                        if( 'draft' === $event['eventbrite']->status ){
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 4 tabs, found 6
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after IF keyword; 0 found
* :no_entry_sign: There must be a space between if and the first parenthesis '('
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: 2a3479d0cf604e05bdec84800d65ef67</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                            $status = 'draft';
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: 5e79e1400f75b7fbb54eb5f96b09f84a</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                        }else{
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 4 tabs, found 6
* :no_entry_sign: Expected 1 space after closing brace; 0 found
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after ELSE keyword; 0 found

<sub>hash: 2103955c15ce2fce87cff0847df85b0d</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                            $status = 'publish';
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: 26a0004866903471543851347effda83</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                        }
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 4 tabs, found 6

<sub>hash: 7f6275457a5e05dbfb0be79d972b5d0b</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                    }else{
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 3 tabs, found 5
* :no_entry_sign: Expected 1 space after closing brace; 0 found
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after ELSE keyword; 0 found

<sub>hash: 4a02f01933107f2532a1580caf8d9899</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                        // if not set, assume publish
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: d6da2aa391870b290027db483c7ef704</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                        $status = 'publish';
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: b4849cac508f7d589aab0704ae20763c</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                    }
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 3 tabs, found 5

<sub>hash: 98ffa119d01b5b0b570ed0b9e609412b</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                    // If not draft, looked if listed. If not, set to private
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: ea0710f85ae761368bb68b645805b901</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                    if( 'draft' !== $status && isset($event['eventbrite']->listed) && !tribe_is_truthy($event['eventbrite']->listed) ){
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 3 tabs, found 5
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after IF keyword; 0 found
* :no_entry_sign: There must be a space between if and the first parenthesis '('
* :no_entry_sign: Expected 1 spaces after opening parenthesis; 0 found
* :no_entry_sign: Expected 1 spaces before closing parenthesis; 0 found
* :no_entry_sign: There must be a single space after the first parenthesis
* :no_entry_sign: There must be a single space before the last parenthesis
* :no_entry_sign: Expected 1 space after "!"; 0 found
* :no_entry_sign: ! must be followed by a single space
* :no_entry_sign: Expected 1 spaces after opening parenthesis; 0 found
* :no_entry_sign: Expected 1 spaces before closing parenthesis; 0 found
* :no_entry_sign: There must be a single space after the first parenthesis
* :no_entry_sign: There must be a single space before the last parenthesis
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: 6e614c39354b37364deb70e791301031</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                        $status = 'private';
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: d8cb9b18a57abbc345811f640f59e50f</sub>

2020-10-30 15:59 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +                    }
* :no_entry_sign: Tabs must be used to indent lines; spaces are not allowed
* :no_entry_sign: Line indented incorrectly; expected 3 tabs, found 5

<sub>hash: 15db73c14c931781a54fbeb4a552e427</sub>

2020-11-11 21:38 UTC, tr1b0t reviewed
:no_entry_sign: 31 error(s)

2020-11-11 21:38 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +			if( isset( $event['eventbrite']->status ) ){
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after IF keyword; 0 found
* :no_entry_sign: There must be a space between if and the first parenthesis '('
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: 290e18fbcf61913f92354e91bf930745</sub>

2020-11-11 21:38 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +				if( 'draft' === $event['eventbrite']->status ){
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after IF keyword; 0 found
* :no_entry_sign: There must be a space between if and the first parenthesis '('
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: c4acffac21c125f80c9b0764e5b50196</sub>

2020-11-11 21:38 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +				}else{
* :no_entry_sign: Expected 1 space after closing brace; 0 found
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after ELSE keyword; 0 found

<sub>hash: 3a54f69426455027934ba8707e14c48a</sub>

2020-11-11 21:38 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +			}else{
* :no_entry_sign: Expected 1 space after closing brace; 0 found
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after ELSE keyword; 0 found

<sub>hash: 9b586a2eeea3c23e78e4a6dd5f271cf5</sub>

2020-11-11 21:38 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +			if( 'draft' !== $status && isset( $event['eventbrite']->listed ) && !tribe_is_truthy( $event['eventbrite']->listed ) ){
* :no_entry_sign: Space after opening control structure is required
* :no_entry_sign: No space before opening parenthesis is prohibited
* :no_entry_sign: Expected 1 space(s) after IF keyword; 0 found
* :no_entry_sign: There must be a space between if and the first parenthesis '('
* :no_entry_sign: Expected 1 space after "!"; 0 found
* :no_entry_sign: ! must be followed by a single space
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: 0548e07f44dc9a4e2d569bec740cdac6</sub>

2020-11-11 21:45 UTC, tr1b0t reviewed
:no_entry_sign: 11 error(s)

2020-11-11 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +			if ( isset( $event['eventbrite']->status ) ){
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: dd8ae1c3533b440893b23b72760a9c57</sub>

2020-11-11 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +				if ( 'draft' === $event['eventbrite']->status ){
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: 7bd7d1fb4b9961683631081ebd71a4a8</sub>

2020-11-11 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +			if ( 'draft' !== $status && isset( $event['eventbrite']->listed ) && !tribe_is_truthy( $event['eventbrite']->listed ) ){
* :no_entry_sign: Expected 1 space after "!"; 0 found
* :no_entry_sign: ! must be followed by a single space
* :no_entry_sign: Expected 1 space(s) after closing parenthesis; found 0
* :no_entry_sign: You must have a space after a closing parenthesis
* :no_entry_sign: Space between opening control structure and closing parenthesis is required

<sub>hash: 8282720e479b428f0fd607b3c023f8a6</sub>

2020-11-11 21:50 UTC, tr1b0t reviewed
:no_entry_sign: 3 error(s)

2020-11-11 21:50 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +			if ( 'draft' ! == $status && isset( $event['eventbrite']->listed ) && !tribe_is_truthy( $event['eventbrite']->listed ) ) {
* :no_entry_sign: PHP syntax error: syntax error, unexpected '!'
* :no_entry_sign: Expected 1 space after "!"; 0 found
* :no_entry_sign: ! must be followed by a single space

<sub>hash: be9ec11c193e4b7bdee79318f8664aef</sub>

2020-11-11 23:08 UTC, mitogh requested changes

2020-11-11 23:08 UTC, mitogh commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +			}
I can recommend to remove the `else` part and make the initial value of the variable instead..

```suggestion
			$status = 'publish';
			if ( isset( $event['eventbrite']->status ) &&  'draft' === $event['eventbrite']->status ) {
				$status = 'draft';
			} 
```

2020-11-11 23:08 UTC, mitogh commented
Ticket: [TEC-3569]

2020-11-11 23:09 UTC, mitogh commented
Would you mind making sure this branch is up to date as well with the branch where is going to be merged `release/B20.11`

2020-11-12 19:46 UTC, tr1b0t reviewed
:no_entry_sign: 1 error(s)

2020-11-12 19:46 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Eventbrite.php
> +			if ( isset( $event['eventbrite']->status ) &&  'draft' === $event['eventbrite']->status ) {
:no_entry_sign: Expected 1 space after "&&"; 2 found

<sub>hash: 0cb93925109f3ddd017a0c29cc8451e4</sub>

2020-11-12 23:41 UTC, mitogh approved these changes

2020-11-13 17:57 UTC, codingmusician commented
@mitogh I was thinking that there was a conflict with the readme file, but there wasn't. I reverted the commit, but it had cancelled out your review. Sorry about that.

2020-11-13 20:54 UTC, mitogh commented
No worries let me take a look.

2020-11-16 14:37 UTC, mitogh commented
Looks like this PR has other changes would you mind making sure those changes are intended and expected? @codingmusician

2020-11-16 18:25 UTC, closed without merging