Use Heart Beat API to consume EA client results.
moderntribe/the-events-calendar pull request #3367
Opened 2020-11-25 21:43 UTC by mitogh

Use the Heart Beath API to pull the status on the progress bar of EA, in this system the poll is done and handling via WordPress instead.

Artifact: http://p.tri.be/iT4IqG

2020-11-25 21:45 UTC, tr1b0t reviewed
:no_entry_sign: 16 error(s)
:warning: 2 warning(s)

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +     * Action to reply every time a heart beat is executed to send the progress of EA if an EA record is present.
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: a7e50cbeb69cd719d001e5786874ac6b</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +     *
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: 752f7c23bd06800ee1669d9a4d14c007</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +	 * @param array<string, mixed> $response The current response object
:no_entry_sign: Parameter comment must end with a full stop

<sub>hash: 903af9ffcb37e2aa0f1e47a264e6f689</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +		if ( $this->record_id === 0 ) {
:no_entry_sign: Use Yoda Condition checks, you must.

<sub>hash: 7ccc1abb8d6e0c4cf636dbc6a9f3e0ad</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +	    _deprecated_function( __METHOD__, 'TBD' );
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: 70c3bd3e8cee83eea7219fa813a0f6fb</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +		$this->record_id = (int) $_POST['record'];
* :no_entry_sign: Processing form data without nonce verification.
* :no_entry_sign: Detected usage of a possibly undefined superglobal array index: $_POST['record']. Use isset() or empty() to check the index exists before using it

<sub>hash: 7455cc53d049d63a1ed9206c700f5197</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +		// Nonce check
:no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: 426e751c4dc78e7dd41edead33ecd14b</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +		$this->ajax_operations->verify_or_exit( $_POST['check'], $this->get_ajax_nonce_action(), $this->get_unable_to_continue_processing_data() );
* :warning: Detected usage of a non-sanitized input variable: $_POST['check']
* :no_entry_sign: Processing form data without nonce verification.
* :no_entry_sign: Detected usage of a possibly undefined superglobal array index: $_POST['check']. Use isset() or empty() to check the index exists before using it

<sub>hash: 27315f957ba769b1be999435a19032ce</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +		$data = $this->get_queue_progress_data();
:warning: Equals sign not aligned with surrounding assignments; expected 6 spaces but found 1 space

<sub>hash: bc39f361851bc533c5a2074079c3eb46</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +		return wp_json_encode( $this->get_progress_data($queue, $percentage, $done) );
* :no_entry_sign: Expected 1 spaces after opening parenthesis; 0 found
* :no_entry_sign: Expected 1 spaces before closing parenthesis; 0 found
* :no_entry_sign: There must be a single space after the first parenthesis
* :no_entry_sign: There must be a single space before the last parenthesis

<sub>hash: cae18937af76e184390c0c441b118e1a</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +		// Load the queue
:no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: d0e730f247632c6910724a444d7e9ab3</sub>

2020-11-25 21:45 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +		// We always need to setup the Current Queue
:no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: 339293a23633d9aada23a257d2ed6464</sub>

2020-11-25 21:51 UTC, tr1b0t reviewed
:no_entry_sign: 6 error(s)

2020-11-25 21:51 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +			tribe_get_request_var('check'),
* :no_entry_sign: Expected 1 spaces after opening parenthesis; 0 found
* :no_entry_sign: Expected 1 spaces before closing parenthesis; 0 found
* :no_entry_sign: There must be a single space after the first parenthesis
* :no_entry_sign: There must be a single space before the last parenthesis

<sub>hash: 320fd98d5213d70ba308d5b6585f1b11</sub>

2020-11-25 21:51 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +            $this->get_ajax_nonce_action(),
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: 702c951d9197fa82e1904392e5a0fd5b</sub>

2020-11-25 21:51 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
> +            $this->get_unable_to_continue_processing_data()
:no_entry_sign: Tabs must be used to indent lines; spaces are not allowed

<sub>hash: c6da15ad100613a85dd03cef5a2a6e42</sub>

2020-11-26 08:46 UTC, lucatume requested changes
This is a neat idea, but the Heartbeat API can be disabled.
I would rely on that, if available, and fall back on the existing system if not available.
Probably scaffold a simple API that our current implementation and the Heartbeat API handler can implement (or share, with a trait), remove knowledge from the JS component of the BE system handling the request by localizing, from the backend, something telling it what endpoint/action to use.
Add tests.

2020-11-26 17:24 UTC, mitogh commented
Great point :)

2020-11-26 20:51 UTC, tr1b0t reviewed
:no_entry_sign: 1 error(s)

2020-11-26 20:51 UTC, tr1b0t commented on src/Tribe/Aggregator/Record/Queue_Realtime.php
>  		add_action( 'wp_ajax_tribe_aggregator_realtime_update', array( $this, 'ajax' ) );
:no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: 7d234b2cc427e8062872a5976d31178c</sub>

2020-11-27 14:14 UTC, lucatume approved these changes
Solve conflicts, then good to merge.

2020-11-27 14:14 UTC, lucatume commented on src/resources/js/aggregator-fields.js
> +		obj.progress.hasHeartBeat = typeof wp !== 'undefined' && wp.heartbeat;
This should probably be a Yoda conditoin.

2020-11-27 15:50 UTC, merged