Customizer style overrides
moderntribe/the-events-calendar pull request #3375
Opened 2020-11-27 14:17 UTC by alliuca

**Description:** Implements the style overrides for the new Customizer V2 settings

**Tickets:**
https://moderntribe.atlassian.net/browse/TEC-3651
https://moderntribe.atlassian.net/browse/TEC-3673
https://moderntribe.atlassian.net/browse/TEC-3334
https://moderntribe.atlassian.net/browse/TEC-3682
https://moderntribe.atlassian.net/browse/TEC-3675

**Screenshots:**

![tec tribe_events_list_](https://user-images.githubusercontent.com/5049893/100457900-260bde00-30c3-11eb-95da-225b201d043f.png)

![Screen Shot 2020-11-27 at 3 03 11 PM](https://user-images.githubusercontent.com/5049893/100457941-3c199e80-30c3-11eb-93d4-d2a09ed765b0.png)

![Screen Shot 2020-11-27 at 3 03 17 PM](https://user-images.githubusercontent.com/5049893/100457963-46d43380-30c3-11eb-8a42-8f925f9bd895.png)

![tec tribe_events_list_ (1)](https://user-images.githubusercontent.com/5049893/100457916-2dcb8280-30c3-11eb-8736-8703f70e14a8.png)

![Screen Shot 2020-11-27 at 3 04 23 PM](https://user-images.githubusercontent.com/5049893/100457985-4cca1480-30c3-11eb-9645-80b900ec3fd7.png)

![tec tribe_events_list_(iPhone X)](https://user-images.githubusercontent.com/5049893/100458044-68cdb600-30c3-11eb-86ca-ba265c4be2ee.png)

![tec tribe_events_month_(iPhone X)](https://user-images.githubusercontent.com/5049893/100458058-6e2b0080-30c3-11eb-9ce6-309d21a1c415.png)

2020-11-27 14:18 UTC, tr1b0t reviewed
:no_entry_sign: 3 error(s)
:warning: 9 warning(s)

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Customizer/Global_Elements.php
> +			'link_color'               => '#141827',
:warning: Array double arrow not aligned correctly; expected 12 space(s) between "'link_color'" and double arrow, but found 15.

<sub>hash: dfcddde436210a7564e5eab2968dc8dc</sub>

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Customizer/Global_Elements.php
> +			'background_color'         => '#e9e4f0', // TODO: use customizer setting
* :warning: Array double arrow not aligned correctly; expected 6 space(s) between "'background_color'" and double arrow, but found 9.
* :no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: f8795d74da2b91ebb6b47a9ef562d5c2</sub>

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Customizer/Global_Elements.php
> +			'event_title_color'        => '#009051', // TODO: use customizer setting
* :warning: Array double arrow not aligned correctly; expected 5 space(s) between "'event_title_color'" and double arrow, but found 8.
* :no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: 5b288140565bbe5fd8512a7b7a28471f</sub>

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Customizer/Global_Elements.php
> +			'event_date_time_color'    => '#D4AF37', // TODO: use customizer setting
* :warning: Array double arrow not aligned correctly; expected 1 space(s) between "'event_date_time_color'" and double arrow, but found 4.
* :no_entry_sign: Inline comments must end in full-stops, exclamation marks, or question marks

<sub>hash: 9bb89e0248fb7423c1654fbd066b638b</sub>

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Customizer/Single_Event.php
> +					color: <%= single_event.post_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 2147cc6af4784659b0c1f5ade73571d6</sub>

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					background-color: <%= global_elements.background_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: c3358811d817a26de5845391ed210699</sub>

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: f09ff371275408f4d5291cc1a342a701</sub>

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					border-color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 1e057b2269c8f37ac458a3ba0e7a2654</sub>

2020-11-27 14:18 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 3ad0deb523ec83268ce68d8b80033f08</sub>

2020-11-30 18:06 UTC, paulmskim requested changes
Looks great! Just a few notes and should be good from there.

2020-11-30 18:06 UTC, paulmskim commented on src/Tribe/Views/V2/Customizer.php
> +				.tribe-events-calendar-day__event-datetime,
I know we're trying to keep specificity down, but we also want to keep our styles targeted, so let's add `.tribe-events` before these 2.

2020-11-30 18:11 UTC, paulmskim commented
Also I forgot to mention, but we'll want to copy over the theme overrides to the customizer as well, as those will likely have a higher specificity and we'll want to override them (twenty seventeen is good at taking over links).

2020-12-01 08:23 UTC, alliuca commented on src/Tribe/Views/V2/Customizer.php
> +				.single-tribe_organizer {
```suggestion
				.tribe-events,
				.single-tribe_events .site-content {
```

can't target `main.tribe-events-pg-template` cause it has auto margins that won't pick up the background color (would have to change it to padding). Is it ok to use body's `single-tribe_events` in the single event page case?

http://p.tri.be/eeemDm

2020-12-01 08:32 UTC, alliuca commented on src/Tribe/Views/V2/Customizer.php
> +				.single-tribe_organizer {
actually, I can't use `.site-content`, some themes don't have it. Ideally we should be able to target `.tribe-events-pg-template` directly. Would maybe be ideal if we had a `.inner` class or something to wrap everything under that main @paulmskim

2020-12-01 09:21 UTC, alliuca commented
> Also I forgot to mention, but we'll want to copy over the theme overrides to the customizer as well, as those will likely have a higher specificity and we'll want to override them (twenty seventeen is good at taking over links).

@paulmskim do we have a list of themes we officially support? I see there's a bunch of different overrides (avada, divi, etc)

2020-12-01 09:48 UTC, paulmskim commented
> > Also I forgot to mention, but we'll want to copy over the theme overrides to the customizer as well, as those will likely have a higher specificity and we'll want to override them (twenty seventeen is good at taking over links).
> 
> @paulmskim do we have a list of themes we officially support? I see there's a bunch of different overrides (avada, divi, etc)

We do. Joel has the full list, but from what I can remember: Twenty Seventeen, Twenty Nineteen (though I believe we've dropped support for this now), Twenty Twenty, Avada, Divi, Enfold, Astra, and Genesis. You should be able to see the theme overrides, though, in the pcss files where you grabbed the specific selectors. At the bottom there should be theme overrides for specific selectors.

2020-12-01 10:21 UTC, alliuca commented on src/Tribe/Views/V2/Customizer.php
> +				.single-tribe_organizer {
used `#tribe-events, #tribe-events-pg-template` as discussed

2020-12-02 14:36 UTC, alliuca commented
@lucatume any idea on why this test fails now? https://travis-ci.com/github/moderntribe/the-events-calendar/builds/205928249#L1094

2020-12-03 09:04 UTC, tr1b0t reviewed
:warning: 6 warning(s)

2020-12-03 09:04 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 8d4357305bd5cd2cd2e47ff4326395ff</sub>

2020-12-03 09:04 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					border-color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 18e332118eb65d8cd364f7acd65ea15d</sub>

2020-12-03 09:04 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 93722b3d3dade62d065cb99f681588f4</sub>

2020-12-03 09:04 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.link_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: d3c61bd54738e050e73227c138871ec1</sub>

2020-12-03 09:04 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					background-color: <%= global_elements.background_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 031ac40b227f60903aef05152271c43d</sub>

2020-12-03 09:04 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= single_event.post_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 023a5e167648f4cfa819111c139db19a</sub>

2020-12-03 09:49 UTC, alliuca commented
don't merge yet, QA will test on the feature branch first

2020-12-03 18:22 UTC, paulmskim approved these changes
Looks great!

2020-12-03 18:37 UTC, tr1b0t reviewed
:warning: 6 warning(s)

2020-12-03 18:37 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: f0e70354584c998418216deb43bf7856</sub>

2020-12-03 18:37 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					border-color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: df403126fabfd0c5ced4b26666f9dc1c</sub>

2020-12-03 18:37 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 092bcf192b4be19fdea7abeccdbc0dad</sub>

2020-12-03 18:37 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.link_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: f693673ec3fdbb72dd063816270855d4</sub>

2020-12-03 18:37 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					background-color: <%= global_elements.background_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: f26c028e95533a27cb30e36dbb8982a9</sub>

2020-12-03 18:37 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= single_event.post_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 83357302cf63c22323f88babf71e261d</sub>

2020-12-03 19:09 UTC, tr1b0t reviewed
:warning: 6 warning(s)

2020-12-03 19:09 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: e241121e95046a92a46b0a905bc05c08</sub>

2020-12-03 19:09 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					border-color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 3ed2038bcd126307e20a8ec99e73b5af</sub>

2020-12-03 19:09 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 605f7b2efed05e6ac8c2222956e556ae</sub>

2020-12-03 19:09 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.link_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 341f9a49528903dc797acf87db3251cc</sub>

2020-12-03 19:09 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					background-color: <%= global_elements.background_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 723da72d8c096c51eea8e31725ff6389</sub>

2020-12-03 19:09 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= single_event.post_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 4e51c8e0ebb1d85787f44c5890d44522</sub>

2020-12-04 09:38 UTC, tr1b0t reviewed
:warning: 8 warning(s)

2020-12-04 09:38 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +				'default' => '#fff',
:warning: Array double arrow not aligned correctly; expected 14 space(s) between "'default'" and double arrow, but found 1.

<sub>hash: 4a126885e2c70e37475a0a64b375364f</sub>

2020-12-04 09:38 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +				'type'    => 'option',
:warning: Array double arrow not aligned correctly; expected 17 space(s) between "'type'" and double arrow, but found 4.

<sub>hash: b0574a29c4eac6afaef1502dad032f33</sub>

2020-12-04 09:38 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 36a6a9b151064597c73740b30f7ec18b</sub>

2020-12-04 09:38 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					border-color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: da4383f7432da5913d42228b165565c9</sub>

2020-12-04 09:38 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: edea167d2889472dd032379d02f1107a</sub>

2020-12-04 09:38 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.link_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 581455745f327e110102e3737142e65c</sub>

2020-12-04 09:38 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					background-color: <%= global_elements.background_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 60f3478ce85ca730bbec331050033390</sub>

2020-12-04 09:38 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= single_event.post_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 4c5270587993720f45af2e70e7ca9346</sub>

2020-12-04 09:39 UTC, paulmskim commented on src/Tribe/Views/V2/Customizer.php
> +				'type'    => 'option',
```suggestion
				'default'              => '#fff',
				'type'                 => 'option',
```

2020-12-04 13:27 UTC, tr1b0t reviewed
:warning: 5 warning(s)

2020-12-04 13:27 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 0f7db381252fee9934fdedb3f401254d</sub>

2020-12-04 13:27 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					border-color: <%= global_elements.event_title_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 8dd3811ce37e52a07930613df9d919d7</sub>

2020-12-04 13:27 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.event_date_time_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: 368f67766efb8b9303ca1a1f539a4c27</sub>

2020-12-04 13:27 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					color: <%= global_elements.link_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: ceb074de0762da923011349890c31829</sub>

2020-12-04 13:27 UTC, tr1b0t commented on src/Tribe/Views/V2/Customizer.php
> +					background-color: <%= global_elements.background_color %>;
:warning: Found Underscore.js unescaped output notation: "<%=".

<sub>hash: e75798ae1536491f5bc6633ed4472ddb</sub>

2020-12-07 18:07 UTC, paulmskim approved these changes

2020-12-07 18:08 UTC, merged