Interim commit
moderntribe/the-events-calendar pull request #3389
Opened 2020-12-04 21:38 UTC by Camwyn

First pass at getting the post tags widget filter to work.

Some changes to go along with https://github.com/moderntribe/events-pro/pull/1639

2020-12-04 21:39 UTC, tr1b0t reviewed
:no_entry_sign: 14 error(s)
:warning: 1 warning(s)

2020-12-04 21:39 UTC, tr1b0t commented on src/Tribe/Views/V2/View.php
> +		bdump('view_setup_repository_args');
* :no_entry_sign: Expected 1 spaces after opening parenthesis; 0 found
* :no_entry_sign: Expected 1 spaces before closing parenthesis; 0 found
* :no_entry_sign: There must be a single space after the first parenthesis
* :no_entry_sign: There must be a single space before the last parenthesis

<sub>hash: b906ba7ed9f89ef08b4d4db0374c381c</sub>

2020-12-04 21:39 UTC, tr1b0t commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +		bdump('widget_setup_repository_args');
* :no_entry_sign: Expected 1 spaces after opening parenthesis; 0 found
* :no_entry_sign: Expected 1 spaces before closing parenthesis; 0 found
* :no_entry_sign: There must be a single space after the first parenthesis
* :no_entry_sign: There must be a single space before the last parenthesis

<sub>hash: dbad249068566b809743b38392432894</sub>

2020-12-04 21:39 UTC, tr1b0t commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +		$context = null !== $context ? $context : $this->context;
:warning: Equals sign not aligned with surrounding assignments; expected 5 spaces but found 1 space

<sub>hash: 0e36dc6e1ee79763ec86060a8095ede8</sub>

2020-12-04 21:39 UTC, tr1b0t commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +		bdump( [
:no_entry_sign: Opening parenthesis of a multi-line function call must be the last content on the line

<sub>hash: ebaeb7952e6686f114ebd36837ee0b0a</sub>

2020-12-04 21:39 UTC, tr1b0t commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +			$args
* :no_entry_sign: Each array item in a multi-line array declaration must end in a comma
* :no_entry_sign: Comma required after last value in array declaration

<sub>hash: 316f344f5436a75c320b71a009840748</sub>

2020-12-04 21:39 UTC, tr1b0t commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +		]
:no_entry_sign: Multi-line function call not indented correctly; expected 12 spaces but found 8

<sub>hash: 0c78af2880fddb7dd3bc3ac8befc7c16</sub>

2020-12-04 21:39 UTC, tr1b0t commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +	);
* :no_entry_sign: Multi-line function call not indented correctly; expected 8 spaces but found 4
* :no_entry_sign: Line indented incorrectly; expected at least 2 tabs, found 1

<sub>hash: da32f78babd7296a14ef2e0cf232462d</sub>

2020-12-07 09:48 UTC, lucatume requested changes

2020-12-07 09:48 UTC, lucatume commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +	 * @return array The arguments, ready to be set on the View repository instance.
```suggestion
	 * @return array<string,mixed> The arguments, ready to be set on the View repository instance.
```

2020-12-07 09:48 UTC, lucatume commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +		$context_arr = $context->to_array();
Nope, let's avoid this as it's costly and inefficient.
Just pass a reference to the context in the filter.

2020-12-07 09:48 UTC, lucatume commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
> +		$args = apply_filters( "tribe_events_views_v2_{$this->get_slug()}_repository_args", $args, $context_arr );
```suggestion
		$args = apply_filters( "tribe_events_views_v2_{$this->get_slug()}_repository_args", $args, $context );
```

Just pass a reference to the context, dumping the context to array is inefficient and an eager resolution of an object optimized for JIT resolution.

2020-12-07 10:28 UTC, paulmskim commented on src/Tribe/Views/V2/Views/Widgets/Widget_View.php
>  use Tribe\Events\Views\V2\View;
can we also fix this spacing?

2020-12-08 03:58 UTC, paulmskim approved these changes

2020-12-08 13:21 UTC, lucatume approved these changes

2020-12-08 17:02 UTC, merged