Fix / TEC-3452 fast forward link copy
moderntribe/the-events-calendar pull request #3408
Opened 2020-12-17 17:05 UTC by alliuca

**Description:** Updates the fast-forward link on the month view so that the plural version of the content type label is used, rather than always showing the hardcoded "events". That comes from the Relabeler extension, if defined ("classes" in the screenshot).

**Ticket:** https://moderntribe.atlassian.net/browse/TEC-3452

**Screenshots:**

![Screen Shot 2020-12-17 at 5 57 40 PM](https://user-images.githubusercontent.com/5049893/102519055-4d3a4780-4092-11eb-899e-aa664d18bcee.png)

2020-12-18 21:15 UTC, Camwyn requested changes
Extra param in the translator notes?

2020-12-18 21:15 UTC, Camwyn commented on src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
> +		/* translators: 1: opening href tag 2: event label singular 3: event label plural 4: closing href tag */
```suggestion
		/* translators: 1: opening href tag 2: event label plural 3: closing href tag */
```

2020-12-21 08:53 UTC, alliuca commented on src/Tribe/Views/V2/Views/Traits/With_Fast_Forward_Link.php
> +		/* translators: 1: opening href tag 2: event label singular 3: event label plural 4: closing href tag */
fixed, thanks

2020-12-21 14:44 UTC, Camwyn submitted a review, later dismissed

2020-12-21 14:44 UTC, Camwyn commented
@alliuca gotta fix the conflicts, but looks good!

2020-12-21 17:27 UTC, alliuca commented
thanks @Camwyn, can you merge yourself? `test (views_ui)` hangs and I can't merge myself (LucaT said he'd look into that)

2020-12-21 17:40 UTC, Camwyn commented
> thanks @Camwyn, can you merge yourself? `test (views_ui)` hangs and I can't merge myself (LucaT said he'd look into that)

I cannot yet either.

2020-12-21 17:42 UTC, Camwyn approved these changes

2020-12-21 17:42 UTC, merged